"""empty message

Revision ID: 31tyz65jpo42_
Revises: 
Create Date: 2022-12-24 11:05:23.232512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31tyz65jpo42_'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('cargo_id', sa.BigInteger(), nullable=False),
    sa.Column('cargo_alici', sa.String(length=255), nullable=True),
    sa.Column('cargo_gonderici', sa.String(length=255), nullable=True),
    sa.Column('cargo_en', sa.Float(), nullable=True),
    sa.Column('cargo_boy', sa.Float(), nullable=True),
    sa.Column('cargo_yukseklik', sa.Float(), nullable=True),
    sa.Column('cargo_agirlik', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cargo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargo')
    # ### end Alembic commands ###
